name: systems.org app0

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
            
      - name: Install dependencies
        run: pip install pytest pytest-cov
      
      - name: Test with pytest
        run: pytest --cov
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: 118dc41a-50b7-40cf-b989-623dcdbe28d5
      # Copy and paste the codecov/test-results-action here
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      # - name: Upload test results to Codecov
      #   if: ${{ !cancelled() }}
      #   uses: codecov/test-results-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      # - name: Upload coverage report as an artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #       name: coverage-report
      #       path: ./htmlcov
    
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #       token: ${{ secrets.CODECOV_TOKEN }}
      #       files: ./coverage.xml
      #       flags: unittests
      #       name: codecov-coverage